task: forecasting
dataset: ETTh1
model: Linear
config_path: configs
log_path: logs/
figs_path: figs/
ckpts_path: ckpts/
resume: false
epochs: 100
learning_rate: 0.001
sync:
  n_channels: 7
  input_len: 96
  output_len: 96
  batch_size: 32
  device: cuda:0
  seed: 1234
  if_sample: true
  sample_size: 64
  cycle: 168
