root_dir: ../Datasets/
task: forecasting
name:
- PEMS03
sync:
  n_channels: 7
  input_len: 96
  output_len: 96
  batch_size: 32
  device: cuda:2
  seed: 1234
  if_sample: false
  sample_size: 64
train_ratio: 0.6
val_ratio: 0.2
test_ratio: 0.2
pred_type: m2m
scale: true
