root_dir: ../Datasets/
task: forecasting
name:
- traffic
sync:
  n_channels: 161
  input_len: 96
  output_len: 96
  batch_size: 1
  device: cuda:0
  seed: 1234
  if_sample: false
  sample_size: 1
  cycle: 168
train_ratio: 0.7
val_ratio: 0.1
test_ratio: 0.2
pred_type: m2m
scale: true
